<div class="container" id="about" style="max-width: 50%">

    <ul class="list-group" style="color:black; 
  text-align: center;">
        <li class="list-group-item">Name : Natrada Sittikorn</li>
        <li class="list-group-item">No : 590610617</li>
        <li class="list-group-item">
            <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/11.jpg'; ?>">
        </li>
    </ul>
    <div class="row" style="padding: 10px;"></div>
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
</div>
