<?php echo $this->flashSession->output();

$username = '';
$password = '';
$rememberMe = '';

if ($this->cookies->has("username") && $this->cookies->has("password")) {
    $username = $this->cookies->get("username");
    $password = $this->cookies->get("password");
    $rememberMe = 'checked';
}
?>
 <!-- Navigation -->
 <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>event">Event</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>about">About</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>contact">Contact</a>
            </li>
          </ul>
           <ul class="navbar-nav  navbar-right">     
   	<?php if($this->session->has('memberAuthen')) {?> 
     
   
      <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about"><?php echo $this->session->get('memberEmail');?></a>
     </li>
     <li class="nav-item mx-0 mx-lg-1">
     		<a  class="btn btn-danger navbar-btn" href="authen/signOut"> Logout </a> 
     </li>  
    <?php } else {?>
      <li class="nav-item mx-0 mx-lg-1">
       <a href="authen" class="btn btn-outline-primary"> Login </a>
      </li>    
     <li class="nav-item mx-0 mx-lg-1">
       <a href="authen/signUp" class="btn btn-outline-info"> Sign Up </a>
      </li>
      <?php }?>
    </ul>
        </div>
      </div>
    </nav>


  <div class="container" id="loginContainer" style="padding-top:10%"> 
    <h2 class="text-center text-uppercase text-secondary mb-0">Login</h2>
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
        <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
        <form name="sentMessage" id="contactForm" novalidate="novalidate" action="" method="post">
          <div class="control-group">
            <div class="form-group floating-label-form-group controls mb-0 pb-2">
              <label>Email</label>
              <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if (isset($username)) {
    echo $username;
}
?>" required>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls mb-0 pb-2">
              <label>Password</label>
              <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if (isset($password)) {
    echo $password;
}
?>" required>
              <p class="help-block text-danger"></p>
            </div>
          </div>

        <div class="form-check form-group">
          <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe; ?>>
          
          <label class="form-check-label" for="rememberMe">Remember me</label>
        </div>
        <div class="form-group text-center" >
          <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-lg">Back</a>
          <button type="submit" class="btn btn-primary btn-lg">Submit</button>
        </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <footer class="page-footer font-small blue pt-4 mt-4">

    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © 2018 Copyright:
        <a href="/Lab/Lab3/phalcon"> Patsakorn Towatrakool </a>
    </div>
    <!--/.Copyright-->

</footer>