<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>event">Event</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>about">About</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo $this->url->getBaseUri(); ?>contact">Contact</a>
            </li>
          </ul>
           <ul class="navbar-nav  navbar-right">     
   	<?php if($this->session->has('memberAuthen')) {?> 
     
   
      <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about"><?php echo $this->session->get('memberEmail');?></a>
     </li>
     <li class="nav-item mx-0 mx-lg-1">
     		<a  class="btn btn-danger navbar-btn" href="signOut"> Logout </a> 
     </li>  
    <?php } else {?>
      <li class="nav-item mx-0 mx-lg-1">
       <a href="../authen" class="btn btn-outline-primary"> Login </a>
      </li>    
     <li class="nav-item mx-0 mx-lg-1">
       <a href="./signUp" class="btn btn-outline-info"> Sign Up </a>
      </li>
      <?php }?>
    </ul>
        </div>
      </div>
    </nav>

<div class="container" style="padding-top:10%">
<h2 class="text-center text-uppercase text-secondary mb-0">Sign Up</h2>
  <div class="row">
    <div class="col-sm">     
      </div>
      <div class="col-sm">
        <form action="" method="post" >
          <input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">
          <div class="form-group">
            <label>Email address</label>
            <input type="email" name="email" class="form-control" id="email" placeholder="Enter email"  required >
          </div>
          <div class="form-group">
            <label>Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
          </div>
          <div class="form-group">
            <label>Firstname</label>
            <input type="text" name="firstname" class="form-control" id="firstname" placeholder="Firstname"  required  >
          </div> 
          
          <button type="submit" class="btn btn-info">Submit</button>
          
          <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
          
        </form>
      </div>
      <div class="col-sm">     
        </div>
      </div>
    </div>
      
      <footer class="page-footer font-small blue pt-4 mt-4">
        
        <!--Copyright-->
        <div class="footer-copyright py-3 text-center">
          © 2018 Copyright:
          <a href="/Lab/Lab3/phalcon"> Natrada Sittikorn </a>
        </div>
        <!--/.Copyright-->
        
      </footer>